#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/random_path_consensus_evaluation
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/random_path_consensus_evaluation
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/random_path_consensus_evaluation nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/random_paths_consensus.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --final_outdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/random_path_consensus_evaluation/ -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/random_path_consensus_evaluation/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_consensus_evaluation/
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_consensus_evaluation/
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/k12_consensus_evaluation nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/k12_consensus.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Loman_K12/loman_k12_pass_porechop.fastq.gz --illumina_reads /nfs/leia/research/iqbal/rmcolq/data/loman_k12/Ecoli_S1_L001_R2_001.fastq.gz --reference_assembly /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/NC_000913.3.fasta --final_outdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_consensus_evaluation/ -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_consensus_evaluation/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_genotyping_evaluation/
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_genotyping_evaluation/
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/k12_genotyping_evaluation nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/k12_genotyping.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Loman_K12/loman_k12_pass_porechop.fastq.gz --illumina_reads1 /nfs/leia/research/iqbal/rmcolq/data/loman_k12/Ecoli_S1_L001_R2_001.fastq.gz --truth_assembly /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/NC_000913.3.fasta --fasta_for_ref /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/NC_000913.3.all.fa --final_outdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_genotyping_evaluation/ -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/k12_genotyping_evaluation/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/single_sample_roc/
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/single_sample_roc/
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/single_sample_roc nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/single_sample_roc.nf --truth_assembly /hps/nobackup/iqbal/mbhall/Pandora_variation/Analysis/Cardio/Polishing/data/H152180645/H152180645_pacbio_assembly.pilon.fa --vcf_directory /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/single_sample_roc/data/ --mask /hps/nobackup/iqbal/mbhall/Pandora_variation/Analysis/Cardio/Polishing/data/H152180645/H152180645_mask.bed --final_outdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/single_sample_roc/ -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/single_sample_roc/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume

