#nextflow run /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/sample_genotype.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --reference_directory /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/refseq/chosen/ --final_outdir /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H131800734/genotyping --pipeline_root /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/ -w /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H131800734/genotyping/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170616/data/porechopped/BC03.fastq.gz --raw_fast5s /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170616/data/reads/ --albacore_summary /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170616/data/basecalled/sequencing_summary.txt --illumina_reads_1 /nfs/leia/research/iqbal/rmcolq/data/cardio/illumina/H131800734.fq --truth_assembly /nfs/leia/research/iqbal/mbhall/Projects/Pandora_variation/Data/Cardio/cardio/pacbio/EColi_4346_assembly.fasta.gz -resume
#nextflow run /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/sample_genotype.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --reference_directory /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/refseq/chosen/ --final_outdir /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H151080744/genotyping --pipeline_root /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/ -w /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H151080744/genotyping/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170412/data/porechopped/BC11.fastq.gz --raw_fast5s /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170412/data/reads/ --albacore_summary /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170412/data/basecalled/sequencing_summary.txt --illumina_reads_1 /nfs/leia/research/iqbal/rmcolq/data/cardio/illumina/H151080744.fq --truth_assembly /nfs/leia/research/iqbal/mbhall/Projects/Pandora_variation/Data/Cardio/cardio/pacbio/EColi_7927_assembly.fasta.gz -resume
#cd /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/CFT073/
#bsub.py 3.0 /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/logs/CFT073_genotyping nextflow run /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/sample_genotype.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --reference_directory /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/refseq/chosen/ --final_outdir /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/CFT073/genotyping --pipeline_root /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/ -w /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/CFT073/genotyping/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config --nanopore_reads /nfs/leia/research/iqbal/rmcolq/data/trace/SRX5299443.fastq --illumina_reads_1 /nfs/leia/research/iqbal/rmcolq/data/trace/SRX5287344.fastq --truth_assembly /nfs/leia/research/iqbal/rmcolq/data/trace/CFT073_subsampled_pacbio.fasta -resume
#cd /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/RHB11-C04/
#bsub.py 3.0 /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/logs/RHB11-C04_genotyping nextflow run /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/sample_genotype.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --reference_directory /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/refseq/chosen/ --final_outdir /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/RHB11-C04/genotyping --pipeline_root /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/ -w /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/RHB11-C04/genotyping/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config --nanopore_reads /nfs/leia/research/iqbal/rmcolq/data/trace/SRX5299467.fastq --illumina_reads_1 /nfs/leia/research/iqbal/rmcolq/data/trace/SRX5287351.fastq --truth_assembly /nfs/leia/research/iqbal/rmcolq/data/trace/RHB11-C04_subsampled_pacbio.fasta -resume

## Copied over samples from yoda to ebi-cli to run pandora compare on
## FROM YODA - did not work from ebi-cli to yoda
# bsub.py 1 logs/rsync_yoda_to_cli_prg rsync -avcr --no-perms /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all rmcolq@ebi-cli.ebi.ac.uk:/nfs/research1/zi/rmcolq/projects/pandora_compare/prg/ecoli/
#bsub.py 1 logs/rsync_yoda_to_cli_ill rsync -avcr --no-perms /nfs/leia/research/iqbal/rmcolq/data/cardio/illumina rmcolq@ebi-cli.ebi.ac.uk:/nfs/research1/zi/rmcolq/projects/pandora_compare/data/cardio/
#bsub.py 1 logs/rsync_yoda_to_cli_nano rsync -avcr --no-perms /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ rmcolq@ebi-cli.ebi.ac.uk:/nfs/research1/zi/rmcolq/projects/pandora_compare/data/cardio/nanopore/

## ON EBI_CLI
#bsub.py 1 logs/download_simg singularity exec 'shub://rmcolq/pandora:pandora' pandora
#mkdir singularity
#mv rmcolq-pandora-dev-pandora.simg singularity/
#bsub.py --queue 'research-rh74' 100 logs/compare_cardio_trace_nano singularity exec singularity/rmcolq-pandora-dev-pandora.simg pandora compare -p /nfs/research1/zi/rmcolq/projects/pandora_compare/prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa -r /nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/read_index_nanopore.tsv -o /nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/nanopore_full --genotype --max_covg 100
#bsub.py --queue 'research-rh74' 60 logs/compare_cardio_trace_ill singularity exec singularity/rmcolq-pandora-dev-pandora.simg pandora compare -p /nfs/research1/zi/rmcolq/projects/pandora_compare/prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa -r /nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/read_index_illumina.tsv -o /nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/illumina --genotype --max_covg 30
#bsub.py --queue 'research-rh74' 30 logs/compare_cardio_trace_nano_30 singularity exec singularity/rmcolq-pandora-dev-pandora.simg pandora compare -p /nfs/research1/zi/rmcolq/projects/pandora_compare/prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa -r /nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/read_index_nanopore.tsv -o /nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/nanopore_30 --genotype --max_covg 30

## Copied compare results back to yoda
bsub.py 1 logs/rsync_cli_to_yoda_ill rsync -avcr --no-perms rmcolq@ebi-cli.ebi.ac.uk:/nfs/research1/zi/rmcolq/projects/pandora_compare/analysis/compare_trace_and_cardio/ /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/4_way_roc/pandora_compare 

