#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/finding_genes_covg
#cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/finding_genes_covg
#bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/finding_genes_covg nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/finding_genes_covg.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/050319_all/ecoli_pangenome_PRG_050319.fa -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/finding_genes_covg/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/parameters nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/parameters.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/050319_all/short_prg.fa -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters/work2 -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters_cluster
#cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters_cluster
#bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/parameters_cluster nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/parameters_cluster.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/050319_all/ecoli_pangenome_PRG_050319.fa --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Loman_K12/loman_k12_pass_porechop.fastq.gz --illumina_reads /nfs/leia/research/iqbal/rmcolq/data/loman_k12/Ecoli_S1_L001_R1_001.fastq.gz -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters_cluster/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters_cluster/30
#cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters_cluster/30
#bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/parameters_cluster_30 nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/parameters_cluster.nf  --covg 30 --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/050319_all/ecoli_pangenome_PRG_050319.fa --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Loman_K12/loman_k12_pass_porechop.fastq.gz --illumina_reads /nfs/leia/research/iqbal/rmcolq/data/loman_k12/Ecoli_S1_L001_R1_001.fastq.gz -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/parameters_cluster/30/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
