## GENOTYPE SNIPPY AND NANOPOLISH
#nextflow run /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/sample_genotype.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --reference_directory /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/refseq/chosen/ --final_outdir /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H131800734/genotyping --pipeline_root /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/ -w /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H131800734/genotyping/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170616/data/porechopped/BC03.fastq.gz --raw_fast5s /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170616/data/reads/ --albacore_summary /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170616/data/basecalled/sequencing_summary.txt --illumina_reads_1 /nfs/leia/research/iqbal/rmcolq/data/cardio/illumina/H131800734.fq --truth_assembly /nfs/leia/research/iqbal/mbhall/Projects/Pandora_variation/Data/Cardio/cardio/pacbio/EColi_4346_assembly.fasta.gz -resume
#nextflow run /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/sample_genotype.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --reference_directory /nfs/leia/research/iqbal/rmcolq/data/references/Escherichia_coli/refseq/chosen/ --final_outdir /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H151080744/genotyping --pipeline_root /nfs/leia/research/iqbal/rmcolq/git/compare_genotypers/nextflow/ -w /nfs/leia/research/iqbal/rmcolq/projects/pandora_variation/analysis/cardio_H151080744/genotyping/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170412/data/porechopped/BC11.fastq.gz --raw_fast5s /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170412/data/reads/ --albacore_summary /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Cardio/ecoli20170412/data/basecalled/sequencing_summary.txt --illumina_reads_1 /nfs/leia/research/iqbal/rmcolq/data/cardio/illumina/H151080744.fq --truth_assembly /nfs/leia/research/iqbal/mbhall/Projects/Pandora_variation/Data/Cardio/cardio/pacbio/EColi_7927_assembly.fasta.gz -resume

## Indexed PanRG for pandora
bsub.py 2 index_prg nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/index_prg.nf --pangenome_prg ecoli_pangenome_PRG_050319.fa --num_prg 37426 --w 19 --k 31 --chunk_size 100 -w work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume    ## /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19
bsub.py 2 index_prg nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/index_prg.nf --pangenome_prg ecoli_pangenome_PRG_050319.fa --num_prg 37426 --w 14 --k 15 --chunk_size 100 -w work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume    ## /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k15.w14

## Ran pandora
bsub.py 60 logs/compare_cardio_illumina_30 singularity exec shub://rmcolq/pandora:pandora pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_30 --genotype --max_covg 30 --illumina --max_diff 32 -w 19 -k 31  
bsub.py 60 logs/compare_cardio_illumina_100 singularity exec shub://rmcolq/pandora:pandora pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_100 --genotype --max_covg 100 --illumina --max_diff 32 -w 19 -k 31 

bsub.py 60 logs/compare_cardio_illumina_100_nopenal singularity exec shub://rmcolq/pandora:pandora pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_100_nopenal --genotype --max_covg 100 --illumina --max_diff 32 -w 19 -k 31 --genotyping_error_rate 1
bsub.py 90 logs/compare_cardio_illumina_150 singularity exec shub://rmcolq/pandora:pandora pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_150 --genotype --max_covg 150 --illumina --max_diff 32 -w 19 -k 31
bsub.py 60 logs/compare_cardio_illumina_100_gaps singularity exec shub://rmcolq/pandora:pandora pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_100_gaps --genotype --max_covg 100 --illumina --max_diff 32 -w 19 -k 31 --min_kmer_covg 1
bsub.py 60 logs/compare_cardio_illumina_100_wk15 singularity exec shub://rmcolq/pandora:pandora pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k15.w14/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_100_wk15 --genotype --max_covg 100 --illumina --max_diff 16 -w 14 -k 15
bsub.py 60 logs/compare_cardio_illumina_100_md63 singularity exec rmcolq-pandora-dev-pandora.simg pandora compare -p /hps/nobackup/iqbal/rmcolq/projects/panrg/ecoli/k31.w19/ecoli_pangenome_PRG_050319.fa -r /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio_read_index_illumina.tsv -o /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/illumina_100_md63 --genotype --max_covg 100 --illumina --max_diff 63 -w 19 -k 31

## Create single sample vcf and ref.fa files for each sample
for run in illumina_30 illumina_100
do
less /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/$run/pandora_multisample_genotyped.vcf | cut -f1-9,10 > /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/genotyping/H131800734/pandora_genotyped_$run.vcf
less /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/$run/pandora_multisample_genotyped.vcf | cut -f1-9,11 > /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/genotyping/H151080744/pandora_genotyped_$run.vcf
cp /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/$run/pandora_multisample.vcf_ref.fa /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/genotyping/H131800734/pandora_genotyped_$run.ref.fa
cp /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/pandora_compare/2_cardio/100419/$run/pandora_multisample.vcf_ref.fa /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/genotyping/H151080744/pandora_genotyped_$run.ref.fa
done

## setup
cd /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only
vim 2_way_roc/genotyped_samples.tsv
cp ../cardio_trace/genotyping/H131800734/snippy_* genotyping/H131800734/
cp ../cardio_trace/genotyping/H131800734/nanopolish_* genotyping/H131800734/
cp ../cardio_trace/genotyping/H151080744/nanopolish_* genotyping/H151080744/
cp ../cardio_trace/genotyping/H151080744/snippy_* genotyping/H151080744/

## Make ROC
#mkdir /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/2_way_roc/100419
cd /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/2_way_roc/100419
bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/cardio_only_roc2 singularity exec /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/singularity/rmcolq-Singularity_recipes-minos.img python3 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/scripts/compare_genotypers_on_number_of_samples.py --sample_tsv /hps/nobackup/iqbal/rmcolq/projects/DPhil_analysis/analysis/cardio_only/2_way_roc/genotyped_samples.tsv
