#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/facing_trees
#cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/facing_trees
#bsub.py 3.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/facing_trees nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/pandora_compare_in_chunks.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --read_index /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio/read_index_illumina.tsv --num_samples 15 --max_covg 50  -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/facing_trees/compare -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#cat pandora_multisample_genotyped.vcf >> vcf_header.txt
#mv vcf_header.txt pandora_multisample_genotyped.vcf
#cat pandora_multisample.matrix >> matrix_header.txt
#mv matrix_header.txt pandora_multisample.matrix
#bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/facing_trees nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/facing_trees.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --read_index /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/data/cardio/read_index_illumina.tsv -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/facing_trees/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/site_frequency_spectrum
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/site_frequency_spectrum
bsub.py 3.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/site_frequency_spectrum nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/pandora_compare_in_chunks.nf --pangenome_prg /nfs/leia/research/iqbal/projects/pandora/klebs/holt_gastro/prg/holt2015/combined_genes_igr10/pangenome_PRG.fa --read_index /nfs/leia/research/iqbal/projects/pandora/klebs/holt_gastro/data/illumina/INDEX --num_samples 150 --max_covg 50  -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/site_frequency_spectrum/compare -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/site_frequency_spectrum nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/site_frequency_spectrum.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/site_frequency_spectrum/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
