#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/finding_genes_covg
#cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/finding_genes_covg
#bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/finding_genes_covg nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/finding_genes_covg.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/050319_all/ecoli_pangenome_PRG_050319.fa -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/finding_genes_covg/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/wk_parameters
cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/wk_parameters
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/wk_parameters nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/wk_parameters.nf  --pangenome_prg /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/indexes/k15.w14/short_prg.fa --index_dir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/indexes -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/wk_parameters/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
#mkdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/cluster_parameters
#cd /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/cluster_parameters
#bsub.py 1.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/cluster_parameters nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/cluster_parameters.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/indexes/k15.w14/short_prg.fa  --index_dir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/indexes -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/cluster_parameters/work2 -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
